### ISSUE TITLE
Good First Issues for Project Enhancement

### ISSUE THREAD

**Issue by mediocre9** [mediocre9/smart-link#178]
1. Develop a feature to save user-defined commands in shared preferences.
2. Improve UI and Aesthetics

**Comment by Babuprasanth27** [comment]
Hey, I am interested in fixing this issue
assign to me.

**Comment by mediocre9** [comment]
> Hey, I am interested in fixing this issue assign to me.

Hi @Babuprasanth27 , Thank you for showing interest in fixing this issue. Due to urgent project requirements, I ended up implementing the features myself. I apologize for not updating or closing the issue promptly.

**Comment by Babuprasanth27** [comment]
@mediocre9 No worry. Just ping me if you want any contribution from my side.Thank you

**Comment by mediocre9** [comment]
@Babuprasanth27 Thanks! I'll definitely reach out to you for future contributions.
